name: Lara Bot 7/24 Auto-Hunter
on:
  schedule:
    - cron: '0 * * * *' # Tam olarak her saat başında otomatik çalışır
  workflow_dispatch: # Senin manuel çalıştırman için buton

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Lara Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python lara_bot.py
